# Physical parameters

offsets:
  shoulder_offset: 0.120 # measured from model
  elbow_offset: 0.027 # measured from model

inertia_parameters:
  base_mass: 2.0  # This mass might be incorrect
  shoulder_mass: 1.98
  upper_arm_mass: 3.4445
  forearm_mass: 1.437
  wrist_1_mass: 0.871
  wrist_2_mass: 0.805
  wrist_3_mass: 0.261

  shoulder_radius: 0.060   # manually measured
  upper_arm_radius: 0.054  # manually measured
  elbow_radius: 0.060      # manually measured
  forearm_radius: 0.040    # manually measured
  wrist_radius: 0.045      # manually measured

  links:
    base:
      radius: 0.075
      length: 0.038

  # model referring to https://www.universal-robots.com/articles/ur/application-installation/dh-parameters-for-calculations-of-kinematics-and-dynamics/
  center_of_mass:
    shoulder_cog:
      x: 0.0        # model.x
      y: 0.0        # -model.z
      z: -0.02      # model.y
    upper_arm_cog:
      x: -0.11355   # model.x - upper_arm_length
      y: 0.0        # model.y
      z: 0.1157     # model.z
    forearm_cog:
      x: -0.1632    # model.x - forearm_length
      y: 0.0        # model.y
      z: 0.0238     # model.z
    wrist_1_cog:
      x: 0.0        # model.x
      y: -0.01      # -model.z
      z: 0.0        # model.y
    wrist_2_cog:
      x: 0.0        # model.x
      y: 0.01       # model.z
      z: 0.0        # -model.y
    wrist_3_cog:
      x: 0.0        # model.x
      y: 0.0        # model.y
      z: -0.02      # model.z

  rotation:
    shoulder:
      roll: 1.570796326794897
      pitch: 0
      yaw: 0
    upper_arm:
      roll: 0
      pitch: 0
      yaw: 0
    forearm:
      roll: 0
      pitch: 0
      yaw: 0
    wrist_1:
      roll: 1.570796326794897
      pitch: 0
      yaw: 0
    wrist_2:
      roll: -1.570796326794897
      pitch: 0
      yaw: 0
    wrist_3:
      roll: 0
      pitch: 0
      yaw: 0

  tensor:
    shoulder:
      ixx: 0.0027657
      ixy: 0.0000096
      ixz: -0.0000149
      iyy: 0.0021501
      iyz: 0.0001873
      izz: 0.0025626
    upper_arm:
      ixx: 0.0042623
      ixy: -0.0000409
      ixz: -0.0014960
      iyy: 0.0460284
      iyz: -0.0000129
      izz: 0.0448947
    forearm:
      ixx: 0.0010511
      ixy: 0.0
      ixz: -0.0000331
      iyy: 0.0113396
      iyz: 0.0000022
      izz: 0.0110895
    wrist_1:
      ixx: 0.0008174
      ixy: -0.0000005
      ixz: 0.0000021
      iyy: 0.0006844
      iyz: 0.0000617
      izz: 0.0005497
    wrist_2:
      ixx: 0.0006059
      ixy: -0.0000006
      ixz: -0.0000006
      iyy: 0.0005837
      iyz: -0.0000271
      izz: 0.0003831
    wrist_3:
      ixx: 0.0001080
      ixy: -0.0000001
      ixz: -0.0000001
      iyy: 0.0001086
      iyz: -0.0000002
      izz: 0.0001371
