[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["ur_kin_py"]

[project]
name = "ur_kin_py"
version = "0.0.1"
dependencies = [
  "numpy<2.0",
  "meshcat",
  "pin",
  "transforms3d",
  "xacrodoc",
]
