# Physical parameters

offsets:
  shoulder_offset: 0.138 # measured from model
  elbow_offset: 0.007 # measured from model

inertia_parameters:
  base_mass: 4.0  # This mass might be incorrect
  shoulder_mass: 3.761
  upper_arm_mass: 8.058
  forearm_mass: 2.846
  wrist_1_mass: 1.37
  wrist_2_mass: 1.3
  wrist_3_mass: 0.365

  shoulder_radius: 0.060   # manually measured
  upper_arm_radius: 0.054  # manually measured
  elbow_radius: 0.060      # manually measured
  forearm_radius: 0.040    # manually measured
  wrist_radius: 0.045      # manually measured

  links:
    base:
      radius: 0.06
      length: 0.05

  # model referring to https://www.universal-robots.com/articles/ur/application-installation/dh-parameters-for-calculations-of-kinematics-and-dynamics/
  center_of_mass:
    shoulder_cog:
      x: 0.0        # model.x
      y: -0.00193   # -model.z
      z: -0.02561   # model.y
    upper_arm_cog:
      x: -0.2125    # model.x - upper_arm_length
      y: 0.0        # model.y
      z: 0.11336    # model.z
    forearm_cog:
      x: -0.2422    # model.x - forearm_length
      y: 0.0        # model.y
      z: 0.0265     # model.z
    wrist_1_cog:
      x: 0.0        # model.x
      y: -0.01634   # -model.z
      z: -0.0018    # model.y
    wrist_2_cog:
      x: 0.0        # model.x
      y: 0.01634    # model.z
      z: -0.0018    # -model.y
    wrist_3_cog:
      x: 0.0        # model.x
      y: 0.0        # model.y
      z: -0.001159  # model.z

  rotation:
    shoulder:
      roll: 1.570796326794897
      pitch: 0
      yaw: 0
    upper_arm:
      roll: 0
      pitch: 0
      yaw: 0
    forearm:
      roll: 0
      pitch: 0
      yaw: 0
    wrist_1:
      roll: 1.570796326794897
      pitch: 0
      yaw: 0
    wrist_2:
      roll: -1.570796326794897
      pitch: 0
      yaw: 0
    wrist_3:
      roll: 0
      pitch: 0
      yaw: 0

  tensor:
    shoulder:
      ixx: 0.00700210
      ixy: 0.00000073
      ixz: -0.00001053
      iyy: 0.00648091
      iyz: 0.00049994
      izz: 0.00657286
    upper_arm:
      ixx: 0.01505885
      ixy: -0.00005400
      ixz: 0.00000563
      iyy: 0.33388086
      iyz: -0.00000181
      izz: 0.33247207
    forearm:
      ixx: 0.00399632
      ixy: -0.00001365
      ixz: 0.00137272
      iyy: 0.07879254
      iyz: -0.00000660
      izz: 0.07848510
    wrist_1:
      ixx: 0.00165491
      ixy: -0.00000282
      ixz: -0.00000438
      iyy: 0.00135962
      iyz: 0.00010157
      izz: 0.00126279
    wrist_2:
      ixx: 0.00135617
      ixy: -0.00000274
      ixz: 0.00000444
      iyy: 0.00127827
      iyz: -0.00005048
      izz: 0.00096614
    wrist_3:
      ixx: 0.00018694
      ixy: 0.00000006
      ixz: -0.00000017
      iyy: 0.00018908
      iyz: -0.00000092
      izz: 0.00025756
